title: Aum Kulkarni
description: Developer, ML Enthusiast, 4th Year Student at VESIT
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

taglong: Developer, ML Enthusiast, 4th Year Student at VESIT
tagshort: Aum Kulkarni Resume

author:
  name: Aum Kulkarni
  email: aum.kulkarni@gmail.com

photo: /assets/files/aum.jpg

# Social media links
social:
  github: SpecularAura
  instagram: aumkulkarni
  linkedin: aum-kulkarni
  stackoverflow: 19804481/specularaura
  blog: blog.aumk.in
